services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: user
      MONGODB_PASSWORD: password
      MONGODB_DB: chat
    volumes:
      - './data:/data/db'
      - './init.sh:/docker-entrypoint-initdb.d/init.sh:ro'
    ports:
      - 27017:27017

  web-app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - HTTP_PORT=3000

      - DB_NAME=chat
      - DB_COLLECTION=messages
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_USER=user
      - DB_PASS=password